version: '3'
services:
  db:
    container_name: confluence_db
    image: mysql:8
    security_opt:
      - seccomp:unconfined
    volumes:
      - /etc/localtime:/etc/localtime
      - ./.data/atlassian/mysql/data:/var/lib/mysql
      - ./.data/atlassian/mysql/mysql-files:/var/lib/mysql-files/
      - ./.data/atlassian/mysql/logs/:/data/mysql/logs/
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: confluence
    restart: always    
    ports:
      - 5306:3306
    command: --default-authentication-plugin=mysql_native_password --skip-name-resolve

  adminer:      
    container_name: confluence_db_viewer
    image: adminer
    restart: always
    links: 
      - db
    ports: 
      - 10092:8080

  confluence:
    container_name: confluence_server
    build: .
    volumes:
      - "./.data/atlassian/confluence-home:/var/atlassian/application-data/confluence"
    links:
      - db
    ports:
      - "8090:8090"
    restart: always    
    environment:
      - JVM_MINIMUM_MEMORY=2048m
      - JVM_MAXIMUM_MEMORY=4096m
      - JVM_RESERVED_CODE_CACHE_SIZE=512m
      - ATL_PROXY_NAME=wiki.dev
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
