version: '2'
services:
  db:
    image: postgres:latest
    volumes:
      - "./.data/db:/var/lib/postgresql"
    restart: always    
    ports:
      - "10091:3306"
    environment:
        POSTGRES_DB: confluence
        POSTGRES_USER: materliu
        POSTGRES_PASSWORD: confluence

  confluence:
    depends_on:
      - db
    image: cptactionhank/atlassian-confluence:6.6.2
    links:
      - db
    ports:
      - "10090:8090"
    restart: always    
    environment: 
      CONFLUENCE_DB_HOST: db:3306
      CONFLUENCE_DB_PASSWORD: confluence
      CONFLUENCE_DB_USER: materliu
      CONFLUENCE_DB_NAME: confluence  

