version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./conf/mysql:/etc/mysql/conf.d"
    restart: always    
    ports:
      - "10091:3306"
    environment:
      MYSQL_ROOT_PASSWORD: confluence
      MYSQL_DATABASE: confluence
      MYSQL_USER: materliu
      MYSQL_PASSWORD: confluence

  confluence:
    depends_on:
      - db
    image: cptactionhank/atlassian-confluence:latest    
    links:
      - db
    ports:
      - "10090:8090"
    restart: always    
    environment: 
      CONFLUENCE_DB_HOST: db:3306
      CONFLUENCE_DB_PASSWORD: confluence
      CONFLUENCE_DB_USER: materliu
      CONFLUENCE_DB_NAME: confluence  

